repos:
  - repo: https://github.com/rhoades-brown/pre-commit.git
    rev: fc077fa1533f657a9382b71327e539ffdf3b036f
    hooks:
      - id: terragrunt-hclfmt
      - id: opentofu-fmt
      - id: opentofu-validate
      - id: tflint
      - id: shellcheck
      - id: gofmt
      - id: golint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
